CREATE TABLE IF NOT EXISTS users (
    uid INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(250) NOT NULL UNIQUE,
    password VARCHAR(250) NOT NULL,
    email VARCHAR(250) NOT NULL UNIQUE,
    token VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS menus (
    user INT PRIMARY KEY REFERENCES users (uid) ON DELETE CASCADE,
    menu VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS storage (
    user INT NOT NULL REFERENCES users (uid) ON DELETE CASCADE,
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    quantity INT NOT NULL,
    expiration DATE NOT NULL,

    UNIQUE (user, name, expiration)
);

CREATE TABLE IF NOT EXISTS shopping (
    user INT NOT NULL REFERENCES users (uid) ON DELETE CASCADE,
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,

    UNIQUE (user, name)
);

CREATE TABLE IF NOT EXISTS ideas (
    user INT NOT NULL REFERENCES users (uid) ON DELETE CASCADE,
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,

    UNIQUE (user, name)
);
