debugging: true

sessionSecret: "xxx"

baseURL: "http://localhost:8080"
port: "8080"

database: "user=cucinassistant password=cucinassistant dbname=cucinassistant ssl-mode=disable"

email:
  address: "cucinassistant@gmail.com"
  server: "<redacted>"
  port: "<redacted>"
  login: "<redacted>"
  password: "<redacted>"
