[EMA_DELETE_CONFIRM]
hash = "sha1-78eee2ae31be61cca084664369bf94f6611f8da9"
other = "per eliminare definitivamente il tuo account, <a href=\"{{ .DeleteLink }}\">clicca qui</a>."

[EMA_GOODBYE]
hash = "sha1-f535a3136ee4df91f0132b116e45c1c09cd58e95"
other = "il tuo account è stato eliminato definitivamente."

[EMA_PASSWORD_CHANGED]
hash = "sha1-b35d68383225e2744ab54cd568f3d8d02fec5557"
other = "la tua password è stata cambiata di recente."

[EMA_RESET_PASSWORD]
hash = "sha1-0400375ded8367df2e37eda027f4f7b251611b28"
other = "per resettare la tua password, <a href=\"{{ .ResetLink }}\">clicca qui</a>."

[ERR_ARTICLE_DUPLICATED]
hash = "sha1-e8bd4ab43729660a5be8cabc9ff165dcd9a7224a"
other = "Esiste già un articolo con stesso nome e scadenza"

[ERR_ARTICLE_EXPIRATION_INVALID]
hash = "sha1-6d6a0c989d3b4a1a5f92bf06107d1b6195259bba"
other = "Scadenza non valida"

[ERR_ARTICLE_NOT_FOUND]
hash = "sha1-aceab162d2fae9dffba793d4ac72b246fbbe7b85"
other = "Articolo non trovata"

[ERR_ARTICLE_QUANTITY_INVALID]
hash = "sha1-85089bc48e309e7f77efd1fd6f8d46737c74aec6"
other = "Quantità non valida"

[ERR_ENTRY_DUPLICATED]
hash = "sha1-f8e084a2d8650b06d93c21286a6b6efe084d4cd6"
other = "Elemento già in lista"

[ERR_ENTRY_NOT_FOUND]
hash = "sha1-998d95bcbc6ec41eca86ca0e7504e531371cb804"
other = "Elemento non trovato"

[ERR_MENU_NOT_FOUND]
hash = "sha1-579b4ac2971a99642e1a0d4c1a18b7b4861b4978"
other = "Menù non trovato"

[ERR_SECTION_DUPLICATED]
hash = "sha1-e14c2c241e36279458fa1336e4c0e5d443920564"
other = "Esiste già una sezione con lo stesso nome"

[ERR_SECTION_NOT_FOUND]
hash = "sha1-17daae9533f73f739ef3828f0028cfb210b324c4"
other = "Sezione non trovata"

[ERR_UNKNOWN]
hash = "sha1-e5fd9aa24c9417e7332e6f25936ae2a6ec8f1524"
other = "Errore sconosciuto"

[ERR_USER_MAIL_INVALID]
hash = "sha1-899a38bce7006977ad73f63becf1341ac4f28cc6"
other = "Email non valida"

[ERR_USER_MAIL_UNAVAIL]
hash = "sha1-73f3a3f213d20d8561065746b31a073231ffa199"
other = "Email non disponibile"

[ERR_USER_NAME_TOO_SHORT]
hash = "sha1-317439217444ee78a5f6d80467d3e8ae70786de1"
other = "Nome utente non valido: lunghezza minima 5 caratteri"

[ERR_USER_NAME_UNAVAIL]
hash = "sha1-c9b61f9d676826708652179850e66d1db8fa6eed"
other = "Nome utente non disponibile"

[ERR_USER_PASS_TOO_SHORT]
hash = "sha1-069c0fd0faf73dad65246b0902ec67932a521be0"
other = "Password non valida: lunghezza minima 8 caratteri"

[ERR_USER_UNKNOWN]
hash = "sha1-3048dd9c09da253d2c7a254f6ee07364a1f30024"
other = "Utente sconosciuto"

[ERR_USER_WRONG_CREDENTIALS]
hash = "sha1-0658dec8ec9871259584e8371bacc483d4a68d09"
other = "Credenziali non valide"

[ERR_USER_WRONG_TOKEN]
hash = "sha1-8d886c0ba6f2b683daba5f19568a316226ce3e4c"
other = "Qualcosa è andato storto"

[MSG_EMAIL_CHANGED]
hash = "sha1-ba6e318074031438a3d25e5d4b6eef5312d15b7c"
other = "Email cambiata con successo"

[MSG_EMAIL_SENT]
hash = "sha1-b2c9a288df4da97877376f398c662b8cded7f597"
other = "Ti abbiamo inviato un'email: controlla la tua casella di posta"

[MSG_LANG_CHANGED]
hash = "sha1-537c815bf1cfd05321911a3ebf8f7487c5526953"
other = "Lingua cambiata correttamente"

[MSG_MENU_DELETED]
hash = "sha1-00c0b7923b6a5cdc03b2d69aff28304c7cb62dad"
other = "Menù elimnato con successo"

[MSG_PAGE_NOT_FOUND]
hash = "sha1-bc3023b36063a7681db24681472b54fa11f0d4ec"
other = "Pagina non trovata"

[MSG_PASSWORD_CHANGED]
hash = "sha1-e12081a4a6d4521224c6eba397f2db9b0f6fb798"
other = "Password cambiata con successo"

[MSG_SECTION_DELETED]
hash = "sha1-3ae5a8b2decbc0d9420a7cc293076c64426b76ef"
other = "Sezione eliminata con successo"

[MSG_SHOPPINGLIST_EMPTIED]
hash = "sha1-6ae41d8106c55ef2780fbd95760270ad43b087b1"
other = "Lista svuotata con successo"

[MSG_UNKNOWN_LANG]
hash = "sha1-e4f2add9e4a52a1731e581cf7bbcb9b6c4b7d77c"
other = "Lingua sconosciuta"

[MSG_UNKNOWN_REQUEST]
hash = "sha1-fe8ec53cd4ffb3bf15a8bb27152cc06ebd59c45b"
other = "Richiesta sconosciuta"

[MSG_UNMATCHING_PASSWORDS]
hash = "sha1-e0be8d69b37fb203c770ac060c490c82053cc520"
other = "Le due password non corrispondono"

[MSG_USERNAME_CHANGED]
hash = "sha1-303a1dcda61b79aebea16014d6d2d92d205a983e"
other = "Nome cambiato con successo"

[MSG_USER_CREATED]
hash = "sha1-d31ca65747477fa7060e86efbad15272b42cb1df"
other = "Account creato con successo"

[MSG_USER_DELETED]
hash = "sha1-c758f56f12fbb48c0b6d8e80b344d4dab6ad5cac"
other = "Account eliminato con successo"

[PAG_INFO]
hash = "sha1-992dfedb89ddbed81ab477592acb4e12c19273f6"
other = "<p>CucinAssistant è un progetto sviluppato da <a href=\"https://gianlucaparri.me\" target=\"_blank\">Gianluca Parri</a>, ideato nel 2023 in seguito alla sua nuova vita da fuorisede universitario.<br>Da quel momento è in continua evoluzione, anche se lentamente.<br>La versione corrente è la {{ .VersionCode }} ({{ .VersionName }}).</p><p> Al momento è disponibile sia come sito web (<a href=\"{{ .BaseURL }}\" target=\"_blank\">{{ .BaseURL }}</a>) sia come applicazione Android sul <a href=\"https://play.google.com/store/apps/details?id=me.gianlucaparri.ca.twa\" target=\"_blank\">Play Store</a>; gli utenti iOS possono installarla dal browser.<br>In ogni caso, le app e il sito sono la stessa identica cosa.</p><p>CucinAssistant è open source; il codice sorgente è disponibile su <a href=\"https://github.com/gianluparri03/cucinassistant/\" target=\"_blank\">GitHub</a>.</p><p>È disponibile una pagina di <a hx-get=\"/stats\">statistiche</a>.</p><p>Per ulteriori informazioni, potete scrivere una mail a <a href=\"mailto:cucinassistant@gmail.com\" target=\"_blank\">cucinassistant@gmail.com</a>.</p>"

[STR_ADD]
hash = "sha1-61cc55aa0453184734c3fa0b621eda6fa874bd83"
other = "Aggiungi"

[STR_ADD_ARTICLES]
hash = "sha1-8294242113aa726c88adcfec51154d164f07a5bb"
other = "Aggiungi articoli"

[STR_APPEND_ENTRIES]
hash = "sha1-998a9915994920b95dd90361c11f9b7e2eb3e4a9"
other = "Aggiungi elementi"

[STR_CANCEL]
hash = "sha1-77dfd2135f4db726c47299bb55be26f7f4525a46"
other = "Annulla"

[STR_CHANGE_EMAIL]
hash = "sha1-dbf1cbcbe39f7f4373fddb35bcc004ab5f5fbd98"
other = "Cambio email"

[STR_CHANGE_PASSWORD]
hash = "sha1-cb1d265a07df179d0e372c15df3fbfebc633fcb8"
other = "Cambio password"

[STR_CHANGE_USERNAME]
hash = "sha1-a5f9f60dd4ecf4c5d074837be0d444f207cdab20"
other = "Cambio nome utente"

[STR_CLONE]
hash = "sha1-d8cdb573350de78596e4852bc9cacfc94e8d17ed"
other = "Clona"

[STR_CONFIRM]
hash = "sha1-04a212215ef9fbf686d280802eb81ee7a6e681cd"
other = "Conferma"

[STR_CURRENT_SEARCH]
hash = "sha1-ecd84a22d5bfc140839422e1b62a8ea68bc7a692"
other = "Ricerca corrente"

[STR_DELETE]
hash = "sha1-f6fdbe48dc54dd86f63097a03bd24094dedd713a"
other = "Elimina"

[STR_DELETE_SECTION_TEXT]
hash = "sha1-f84a6d3ec22389ab7b9393c4bbb20d60e651f351"
other = "Sei sicuro? Tutti gli articoli in questa sezione verranno eliminati."

[STR_DELETE_SELECTED]
hash = "sha1-8516a714a234229b40bbb31b667190177b88c266"
other = "Elimina selezionati"

[STR_DELETE_USER]
hash = "sha1-1753c2061c676db8dd89101b51b92f09a277f51c"
other = "Elimina account"

[STR_DELETE_USER_TEXT1]
hash = "sha1-b4853b495bd891d966bd307fc5dc29a2fd7685e4"
other = "Sei sicuro di voler eliminare il tuo account?"

[STR_DELETE_USER_TEXT2]
hash = "sha1-21323f3a7217636dead622b390e5d045d5d2f3c8"
other = "Sei DAVVERO sicuro di voler eliminare il tuo account? Questa azione è irreversibile."

[STR_EDIT]
hash = "sha1-5301648dcf6b53cefc9ed52999aaa92d4603cae0"
other = "Modifica"

[STR_EDIT_ARTICLE]
hash = "sha1-28e80f82c94d88a7e9a32272306b2ea0b5f05eca"
other = "Modifica articolo"

[STR_EDIT_ENTRY]
hash = "sha1-65440fe7aa25c746a5164314cefa99b603acfbc0"
other = "Modifica elemento"

[STR_EDIT_SECTION]
hash = "sha1-404c66f0e458388dbf332f8d3fc72d66ace5bbdc"
other = "Modifica sezione"

[STR_EMAIL]
hash = "sha1-84add5b2952787581cb9a8851eef63d1ec75d22b"
other = "Email"

[STR_EXPIRATION]
hash = "sha1-f947e853707c30ec094661ee588ce14a79b397c3"
other = "Scadenza"

[STR_FORGOT_PASSWORD]
hash = "sha1-5ed1174bc89211aabf6674c25207c571ed7fa0dc"
other = "Password dimenticata"

[STR_FRIDAY]
hash = "sha1-d166e844a3f3f87149cc4f866eb998e9a751c72a"
other = "Venerdì"

[STR_GOOD_MORNING]
hash = "sha1-890c64abfcf32954ed32fd00ca5ed4c5bc332f9a"
other = "Buongiorno {{ .Username }},"

[STR_INFO]
hash = "sha1-4c53eb52568a369776f7d6d6c6ab28215de64ed2"
other = "Maggiori informazioni"

[STR_LANGUAGE]
hash = "sha1-89b86ab0e66f527166d98df92ddbcf5416ed58f6"
other = "Lingua"

[STR_LOGOUT]
hash = "sha1-e43d612e11f1568f2373e719d4c4b08dcecdc7cc"
other = "Esci"

[STR_MENUS]
hash = "sha1-e7c3800e31ff2e7695b9f5bed95a6de6715dca44"
other = "Menù"

[STR_MONDAY]
hash = "sha1-932eeb1076c85e522f02e15441fa371e3fd000ac"
other = "Lunedì"

[STR_NAME]
hash = "sha1-709a23220f2c3d64d1e1d6d18c4d5280f8d82fca"
other = "Nome"

[STR_NEW_EMAIL]
hash = "sha1-b07e22b0ea81e13b7af3416c00f058561a39c064"
other = "Nuova email"

[STR_NEW_MENU]
hash = "sha1-612fda297a3ae5ecc82577528247c9fe2b2f6b6d"
other = "Nuovo menù"

[STR_NEW_PASSWORD]
hash = "sha1-d850ee188c7c55b64bc3624534de5c5051a57dc6"
other = "Nuova password"

[STR_NEW_SECTION]
hash = "sha1-f10051f6c4d1a10bab68cb30f84e1cf819be5513"
other = "Nuova sezione"

[STR_NEW_USERNAME]
hash = "sha1-d48b52683f7d85cf8d733163c6b05cd6a4380899"
other = "Nuovo nome utente"

[STR_NOREPLY]
hash = "sha1-751e4a1fb2325efec61ee3df177e1defe44ef5b6"
other = "Questa email è stata generata automaticamente. Si prega di non rispondere."

[STR_OK]
hash = "sha1-b0a98216a32426b9e66a4ac1eb6df2e96e1b495c"
other = "Va bene"

[STR_OLD_PASSWORD]
hash = "sha1-e3053fbaa7622ccae5f59565e7fb553f9c2d79c8"
other = "Vecchia password"

[STR_PASSWORD]
hash = "sha1-8be3c943b1609fffbfc51aad666d0a04adf83c9d"
other = "Password"

[STR_QUANTITY]
hash = "sha1-44f6af6945544c0bab016a9160df6abb0cefcb60"
other = "Quantità"

[STR_REGARDS]
hash = "sha1-f39492f77c8ada5234e54eb4bba72e79722912b5"
other = "Saluti,<br>CucinAssistant"

[STR_REPEAT_PASSWORD]
hash = "sha1-366c2415f45eda358aa31b5d67c61f41a43a2bd0"
other = "Ripeti password"

[STR_RESET_PASSWORD]
hash = "sha1-5c4bc97ee5d0ac344829dbcef02d7302feb098a8"
other = "Reset password"

[STR_SATURDAY]
hash = "sha1-17063c506b81a46c2eb7716af50cf19d4ed5a6c6"
other = "Sabato"

[STR_SAVE]
hash = "sha1-efc007a393f66cdb14d57d385822a3d9e36ef873"
other = "Salva"

[STR_SEARCH_ARTICLES]
hash = "sha1-809b141a7641a2b2e915a9cf9fa83b132064fcc7"
other = "Ricerca articoli"

[STR_SECTIONS]
hash = "sha1-cea828c52cd8fb8249d738b3120788e53767c3d3"
other = "Sezioni della dispensa"

[STR_SECTION_EMPTY]
hash = "sha1-b30c74359d59c4b8348460bb85168675fc1da41e"
other = "Questa sezione è vuota."

[STR_SETTINGS]
hash = "sha1-c7f73bb54d928922c3838bb789ee9fb8a5b1eb37"
other = "Impostazioni"

[STR_SET_EMAIL_LANG]
hash = "sha1-e28573c462240d8e1b9307c1b3bf513e86abb036"
other = "Imposta lingua delle email"

[STR_SHOPPINGLIST]
hash = "sha1-44f44c815f3ebb9b9efef94c6c93b8645cf01bd7"
other = "Lista della spesa"

[STR_SHOPPINGLIST_EMPTY]
hash = "sha1-1c290077407cc9f957fbc25de0ef3094545090b7"
other = "La lista è vuota."

[STR_SIGNIN]
hash = "sha1-ada2e9e96fa9ce85430225b412068b5b62b79800"
other = "Accedi"

[STR_SIGNUP]
hash = "sha1-0b81497c8589af2714a1ddbeb62b3a4be679c318"
other = "Registrati"

[STR_STATS]
hash = "sha1-2086b21f8f49274138c38d476bee317a84a8aecc"
other = "Statistiche"

[STR_STATS_ARTICLES]
hash = "sha1-c1d05110004325b5ba56b5a510022bba95491c34"
other = "{{ .Stats.ArticlesNumber }} articoli, divisi in {{ .Stats.SectionsNumber }} sezioni"

[STR_STATS_ENTRIES]
hash = "sha1-4d750ce30e6aedf0f4c4218f93c66af1ac86d5dd"
other = "{{ .Stats.EntriesNumber }} elementi nelle liste della spesa"

[STR_STATS_MENUS]
hash = "sha1-460363d4d02118c9657452c7129704b011dce68a"
other = "{{ .Stats.MenusNumber }} menù"

[STR_STATS_USERS]
hash = "sha1-9b8a0e7fd37e0a24aece9b5d1eebeff4e47459fd"
other = "{{ .Stats.UsersNumber }} utenti"

[STR_STORAGE]
hash = "sha1-9e092dda4f0e27d0c7686ddd00272079e678b6e6"
other = "Dispensa"

[STR_SUNDAY]
hash = "sha1-bc5dd045b8623ddfc4bd0bce98ca5fda42accf88"
other = "Domenica"

[STR_THURSDAY]
hash = "sha1-76031ddf92450ba52c1e3945097079807a9065c2"
other = "Giovedì"

[STR_TUESDAY]
hash = "sha1-42e43b612a5dfae57ddf5929f0fb945ae83cbf61"
other = "Martedì"

[STR_TUTORIAL]
hash = "sha1-2701a94c0eb55cbd958a87dff3e959673ff1bf53"
other = "Guida"

[STR_USERNAME]
hash = "sha1-84c29015de33e5d22422382a372caba5c58f8c01"
other = "Nome utente"

[STR_WEDNESDAY]
hash = "sha1-5656b9b79b0316fc611a9c30d2ffac25228b8371"
other = "Mercoledì"

[STR_WELCOMEBACK]
hash = "sha1-6ed09c2005d90b402bfdb7e04c8cf0a4d60239ca"
other = "Bentornato/a, {{ .Username }}!"

[STR_WELCOME_TO_CA]
hash = "sha1-4d70a53086c4d9e22ae529a8dfd43c7214bd1f40"
other = "Benvenuto su CucinAssistant, {{ .Username }}!"
