STR_ADD = "Add"
STR_ADD_ARTICLES = "Add articles"
STR_APPEND_ENTRIES = "Add entries"
STR_CANCEL = "Cancel"
STR_CHANGE_EMAIL = "Email change"
STR_CHANGE_PASSWORD = "Password change"
STR_CHANGE_USERNAME = "Username change"
STR_CLONE = "Clone"
STR_CONFIRM = "Confirm"
STR_CURRENT_SEARCH = "Current search"
STR_DELETE = "Delete"
STR_DELETE_SECTION_TEXT = "Are you sure? All the articles inside this section will be deleted."
STR_DELETE_SELECTED = "Delete selected"
STR_DELETE_USER = "Delete account"
STR_DELETE_USER_TEXT1 = "Are you sure to delete your account?"
STR_DELETE_USER_TEXT2 = "Are you REALLY sure to delete your account? This action is irreversible."
STR_EDIT = "Edit"
STR_EDIT_ARTICLE = "Edit article"
STR_EDIT_ENTRY = "Edit entry"
STR_EDIT_SECTION = "Edit section"
STR_EMAIL = "Email"
STR_EXPIRATION = "Expiration date"
STR_FORGOT_PASSWORD = "Forgot password"
STR_FRIDAY = "Friday"
STR_INFO = "Info"
STR_LOGOUT = "Logout"
STR_MENUS = "Menus"
STR_MONDAY = "Monday"
STR_NAME = "Name"
STR_NEW_EMAIL = "New email"
STR_NEW_MENU = "New menu"
STR_NEW_PASSWORD = "New password"
STR_NEW_SECTION = "New section"
STR_NEW_USERNAME = "New username"
STR_OLD_PASSWORD = "Old password"
STR_PASSWORD = "Password"
STR_QUANTITY = "Quantity"
STR_REPEAT_PASSWORD = "Repeat password"
STR_RESET_PASSWORD = "Reset password"
STR_SATURDAY = "Saturday"
STR_SAVE = "Save"
STR_SEARCH_ARTICLES = "Search articles"
STR_SECTIONS = "Storage sections"
STR_SECTION_EMPTY = "This section is empty."
STR_SETTINGS = "Settings"
STR_SHOPPINGLIST = "Shopping list"
STR_SHOPPINGLIST_EMPTY = "The list is empty."
STR_SIGNIN = "Sign in"
STR_SIGNUP = "Sign up"
STR_STATS = "Statistics"
STR_STATS_ARTICLES = "{{ .Stats.ArticlesNumber }} articles, divided into {{ .Stats.SectionsNumber }} sections"
STR_STATS_ENTRIES = "{{ .Stats.EntriesNumber }} entries inside the shopping lists"
STR_STATS_MENUS = "{{ .Stats.MenusNumber }} menus"
STR_STATS_USERS = "{{ .Stats.UsersNumber }} users"
STR_STORAGE = "Storage"
STR_SUNDAY = "Sunday"
STR_THURSDAY = "Thursday"
STR_TUESDAY = "Tuesday"
STR_TUTORIAL = "Tutorial"
STR_USERNAME = "Username"
STR_WEDNESDAY = "Wednesday"
STR_WELCOMEBACK = "Welcome back, {{ .Username }}!"
