ERR_ARTICLE_DUPLICATED = "An article with this name and expiration already exists"
ERR_ARTICLE_EXPIRATION_INVALID = "Invalid expiration"
ERR_ARTICLE_NOT_FOUND = "Article not found"
ERR_ARTICLE_QUANTITY_INVALID = "Invalid quantity"
ERR_ENTRY_DUPLICATED = "Entry already in list"
ERR_ENTRY_NOT_FOUND = "Entry not found"
ERR_MENU_NOT_FOUND = "Menu not found"
ERR_SECTION_DUPLICATED = "A section with this name already exists"
ERR_SECTION_NOT_FOUND = "Section not found"
ERR_UNKNOWN = "Unknown error"
ERR_USER_MAIL_INVALID = "Invalid email"
ERR_USER_MAIL_UNAVAIL = "Email not available"
ERR_USER_NAME_TOO_SHORT = "Invalid username: must be at least 5 characters long"
ERR_USER_NAME_UNAVAIL = "Username not available"
ERR_USER_PASS_TOO_SHORT = "Invalid password: must be at least 8 characters long"
ERR_USER_UNKNOWN = "Unknown user"
ERR_USER_WRONG_CREDENTIALS = "Wrong credentials"
ERR_USER_WRONG_TOKEN = "Something went wrong"
MSG_EMAIL_CHANGED = "Email changed succesfully"
MSG_EMAIL_SENT = "We've sent you an email: please, check your inbox"
MSG_LANG_CHANGED = "Language switched successfully"
MSG_MENU_DELETED = "Menu deleted succesfully"
MSG_PAGE_NOT_FOUND = "Page not found"
MSG_PASSWORD_CHANGED = "Password changed successfully"
MSG_SECTION_DELETED = "Section deleted successfully"
MSG_SHOPPINGLIST_EMPTIED = "Entries deleted successfully"
MSG_UNKNOWN_LANG = "Unknown language"
MSG_UNKNOWN_REQUEST = "Unknown request"
MSG_UNMATCHING_PASSWORDS = "The two passwords do not match"
MSG_USERNAME_CHANGED = "Username changed succesfully"
MSG_USER_CREATED = "Account created succesfully"
MSG_USER_DELETED = "Account deleted succesfully"
STR_ADD = "Add"
STR_ADD_ARTICLES = "Add articles"
STR_APPEND_ENTRIES = "Add entries"
STR_CANCEL = "Cancel"
STR_CHANGE_EMAIL = "Email change"
STR_CHANGE_PASSWORD = "Password change"
STR_CHANGE_USERNAME = "Username change"
STR_CLONE = "Clone"
STR_CONFIRM = "Confirm"
STR_CURRENT_SEARCH = "Current search"
STR_DELETE = "Delete"
STR_DELETE_SECTION_TEXT = "Are you sure? All the articles inside this section will be deleted."
STR_DELETE_SELECTED = "Delete selected"
STR_DELETE_USER = "Delete account"
STR_DELETE_USER_TEXT1 = "Are you sure to delete your account?"
STR_DELETE_USER_TEXT2 = "Are you REALLY sure to delete your account? This action is irreversible."
STR_EDIT = "Edit"
STR_EDIT_ARTICLE = "Edit article"
STR_EDIT_ENTRY = "Edit entry"
STR_EDIT_SECTION = "Edit section"
STR_EMAIL = "Email"
STR_EXPIRATION = "Expiration date"
STR_FORGOT_PASSWORD = "Forgot password"
STR_FRIDAY = "Friday"
STR_INFO = "Further informations"
STR_INFO_TEXT = "<p>CucinAssistant is a project developed by <a href=\"https://gianlucaparri.me\" target=\"_blank\">Gianluca Parri</a>, ideated in 2023 thanks to its new life as <i>fuorisede</i>.<br>Since that day it is costantly improving, even if slowly.<br>The current version is the {{ .VersionCode }} ({{ .VersionName }}).</p><p>At the moment it is available both as a website (<a href=\"{{ .BaseURL }}\" target=\"_blank\">{{ .BaseURL }}</a>) and an Android app on the <a href=\"https://play.google.com/store/apps/details?id=me.gianlucaparri.ca.twa\" target=\"_blank\">Play Store</a>; the iOS user can install it from the browser.<br>Anyway, the apps and the website are the exact same thing.</p><p>CucinAssistant is open source: the source code is available on <a href=\"https://github.com/gianluparri03/cucinassistant/\" target=\"_blank\">GitHub</a>.<p>It is available a <a hx-get=\"/stats\">statistics page</a>.</p><p> For further informations, you can send an email at <a href=\"mailto:cucinassistant@gmail.com\" target=\"_blank\">cucinassistant@gmail.com</a>.</p>"
STR_LANGUAGE = "Language"
STR_LOGOUT = "Logout"
STR_MENUS = "Menus"
STR_MONDAY = "Monday"
STR_NAME = "Name"
STR_NEW_EMAIL = "New email"
STR_NEW_MENU = "New menu"
STR_NEW_PASSWORD = "New password"
STR_NEW_SECTION = "New section"
STR_NEW_USERNAME = "New username"
STR_OK = "Ok"
STR_OLD_PASSWORD = "Old password"
STR_PASSWORD = "Password"
STR_QUANTITY = "Quantity"
STR_REPEAT_PASSWORD = "Repeat password"
STR_RESET_PASSWORD = "Reset password"
STR_SATURDAY = "Saturday"
STR_SAVE = "Save"
STR_SEARCH_ARTICLES = "Search articles"
STR_SECTIONS = "Storage sections"
STR_SECTION_EMPTY = "This section is empty."
STR_SETTINGS = "Settings"
STR_SHOPPINGLIST = "Shopping list"
STR_SHOPPINGLIST_EMPTY = "The list is empty."
STR_SIGNIN = "Sign in"
STR_SIGNUP = "Sign up"
STR_STATS = "Statistics"
STR_STATS_ARTICLES = "{{ .Stats.ArticlesNumber }} articles, divided into {{ .Stats.SectionsNumber }} sections"
STR_STATS_ENTRIES = "{{ .Stats.EntriesNumber }} entries inside the shopping lists"
STR_STATS_MENUS = "{{ .Stats.MenusNumber }} menus"
STR_STATS_USERS = "{{ .Stats.UsersNumber }} users"
STR_STORAGE = "Storage"
STR_SUNDAY = "Sunday"
STR_THURSDAY = "Thursday"
STR_TUESDAY = "Tuesday"
STR_TUTORIAL = "Tutorial"
STR_USERNAME = "Username"
STR_WEDNESDAY = "Wednesday"
STR_WELCOMEBACK = "Welcome back, {{ .Username }}!"
