package langs

import (
	"cucinassistant/database"
)

// String is a known string that can be translated into all
// the languages, and have an optional argument
//
//go:generate stringer -type=String
type String int

const (
	STR_NONE String = 0

	str_begin String = String(iota + database.ErrorsNumber)

	STR_ADD
	STR_ADD_ARTICLES
	STR_ALL_ARTICLES
	STR_APPEND_ENTRIES
	STR_ARTICLES
	STR_ARTICLES_ADDED
	STR_CANCEL
	STR_CHANGE_EMAIL
	STR_CHANGE_PASSWORD
	STR_CHANGE_USERNAME
	STR_CLICK_HERE
	STR_CLONE
	STR_CONFIRM
	STR_CURRENT_SEARCH
	STR_DELETE
	STR_DELETE_CONFIRM_EMAIL
	STR_DELETE_LINK
	STR_DELETE_MENU
	STR_DELETE_MENU_TEXT
	STR_DELETE_RECIPE
	STR_DELETE_RECIPE_TEXT
	STR_DELETE_SECTION_TEXT
	STR_DELETE_SELECTED
	STR_DELETE_USER
	STR_DELETE_USER_TEXT1
	STR_DELETE_USER_TEXT2
	STR_DIRECTIONS
	STR_EDIT
	STR_EDIT_ARTICLE
	STR_EDIT_ENTRY
	STR_EDIT_MENU
	STR_EDIT_RECIPE
	STR_EDIT_SECTION
	STR_EMAIL
	STR_EMAIL_CHANGED
	STR_EMAIL_LANG
	STR_EMAIL_SENT
	STR_EMAIL_SETTINGS
	STR_EXPIRATION
	STR_FORGOT_PASSWORD
	STR_FRIDAY
	STR_GENERATE_LINK
	STR_GOOD_MORNING
	STR_GOODBYE
	STR_GOODBYE_EMAIL
	STR_INFO
	STR_INGREDIENTS
	STR_LANG_CHANGED
	STR_LANGUAGE
	STR_LOGOUT
	STR_MENU_DELETED
	STR_MENUS
	STR_MONDAY
	STR_NAME
	STR_NEW_EMAIL
	STR_NEW_MENU
	STR_NEW_PASSWORD
	STR_NEW_RECIPE
	STR_NEW_SECTION
	STR_NEW_USERNAME
	STR_NOREPLY
	STR_NOTES
	STR_OK
	STR_OLD_PASSWORD
	STR_ORDER_CHANGED
	STR_PAGE_NOT_FOUND
	STR_PASSWORD
	STR_PASSWORD_CHANGED
	STR_PASSWORD_CHANGED_EMAIL
	STR_PRINT
	STR_QUANTITY
	STR_RECIPE_DELETED
	STR_RECIPE_IS_SHARED
	STR_RECIPE_IS_UNSHARED
	STR_RECIPE_SAVED
	STR_RECIPES
	STR_RECIPES_EMPTY
	STR_REGARDS
	STR_REGENERATE_LINK
	STR_REPEAT_PASSWORD
	STR_RESET_PASSWORD
	STR_RESET_PASSWORD_EMAIL
	STR_SATURDAY
	STR_SAVE
	STR_SEARCH_ARTICLES
	STR_SEARCH_EMPTY
	STR_SECTION
	STR_SECTION_DELETED
	STR_SECTION_EMPTY
	STR_SECTIONS
	STR_SETTINGS
	STR_SETTINGS_SAVED
	STR_SHARE
	STR_SHOPPINGLIST
	STR_SHOPPINGLIST_EMPTIED
	STR_SHOPPINGLIST_EMPTY
	STR_SIGNIN
	STR_SIGNUP
	STR_SIGNUP_DONE
	STR_STARS
	STR_STATS
	STR_STATS_ARTICLES
	STR_STATS_ENTRIES
	STR_STATS_MENUS
	STR_STATS_RECIPES
	STR_STATS_SECTIONS
	STR_STATS_USERS
	STR_STORAGE
	STR_STORAGE_EMPTY
	STR_SUNDAY
	STR_SUPPORT
	STR_THURSDAY
	STR_TUESDAY
	STR_TUTORIAL
	STR_UNKNOWN_LANG
	STR_UNKNOWN_REQUEST
	STR_UNMATCHING_PASSWORDS
	STR_UNSUBSCRIBE
	STR_USER_CREATED
	STR_USER_DELETED
	STR_USERNAME
	STR_USERNAME_CHANGED
	STR_WANT_NEWSLETTER
	STR_WEDNESDAY
	STR_WELCOME_EMAIL
	STR_WELCOMEBACK

	str_end
)
