package database

//go:generate stringer -type=CAError
type CAError int

// Errors returns the error name
func (c CAError) Error() string {
	return c.String()
}

const (
	ERR_UNKNOWN CAError = iota

	ERR_USER_UNKNOWN
	ERR_USER_NAME_TOO_SHORT
	ERR_USER_NAME_UNAVAIL
	ERR_USER_MAIL_INVALID
	ERR_USER_MAIL_UNAVAIL
	ERR_USER_PASS_TOO_SHORT
	ERR_USER_WRONG_CREDENTIALS
	ERR_USER_WRONG_TOKEN

	ERR_MENU_NOT_FOUND

	ERR_SECTION_DUPLICATED
	ERR_SECTION_NOT_FOUND
	ERR_ARTICLE_NOT_FOUND
	ERR_ARTICLE_QUANTITY_INVALID
	ERR_ARTICLE_EXPIRATION_INVALID
	ERR_ARTICLE_DUPLICATED

	ERR_ENTRY_NOT_FOUND
	ERR_ENTRY_DUPLICATED

	ERR_RECIPE_NOT_FOUND
	ERR_RECIPE_DUPLICATED
)
