package database

import (
	"errors"
)

var (
	ERR_UNKNOWN = errors.New("ERR_UNKNOWN")

	ERR_USER_UNKNOWN           = errors.New("ERR_USER_UNKNOWN")
	ERR_USER_NAME_TOO_SHORT    = errors.New("ERR_USER_NAME_TOO_SHORT")
	ERR_USER_NAME_UNAVAIL      = errors.New("ERR_USER_NAME_UNAVAIL")
	ERR_USER_MAIL_INVALID      = errors.New("ERR_USER_MAIL_INVALID")
	ERR_USER_MAIL_UNAVAIL      = errors.New("ERR_USER_MAIL_UNAVAIL")
	ERR_USER_PASS_TOO_SHORT    = errors.New("ERR_USER_PASS_TOO_SHORT")
	ERR_USER_WRONG_CREDENTIALS = errors.New("ERR_USER_WRONG_CREDENTIALS")
	ERR_USER_WRONG_TOKEN       = errors.New("ERR_USER_WRONG_TOKEN")

	ERR_MENU_NOT_FOUND = errors.New("ERR_MENU_NOT_FOUND")

	ERR_SECTION_DUPLICATED         = errors.New("ERR_SECTION_DUPLICATED")
	ERR_SECTION_NOT_FOUND          = errors.New("ERR_SECTION_NOT_FOUND")
	ERR_ARTICLE_NOT_FOUND          = errors.New("ERR_ARTICLE_NOT_FOUND")
	ERR_ARTICLE_QUANTITY_INVALID   = errors.New("ERR_ARTICLE_QUANTITY_INVALID")
	ERR_ARTICLE_EXPIRATION_INVALID = errors.New("ERR_ARTICLE_EXPIRATION_INVALID")
	ERR_ARTICLE_DUPLICATED         = errors.New("ERR_ARTICLE_DUPLICATED")

	ERR_ENTRY_NOT_FOUND  = errors.New("ERR_ENTRY_NOT_FOUND")
	ERR_ENTRY_DUPLICATED = errors.New("ERR_ENTRY_DUPLICATED")
)
