debugging: true

sessionSecret: "<...>"

baseURL: "http://localhost:8080"
port: "8080"

database: "user=cucinassistant password=cucinassistant dbname=cucinassistant ssl-mode=disable"

email:
  address: "<...>"
  server: "<...>"
  port: "<...>"
  login: "<...>"
  password: "<...>"
