name: Tests
on: [push]

jobs:
  tester:
    name: Runs the tests
    runs-on: ubuntu-latest
    container: golang:1.23

    services:
      database:
        image: postgres
        env:
          POSTGRES_USER: cucinassistant
          POSTGRES_PASSWORD: cucinassistant
          POSTGRES_DB: cucinassistant
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Install dependencies
        run: go get .
      - name: Run tests
        env:
            CA_ENV: "testing_ci"
        run: go test cucinassistant/database cucinassistant/langs
