name: Tests
on: [push]

jobs:
  tester:
    name: Runs the tests and sends the report to Codacy
    runs-on: ubuntu-latest
    container: golang:1.23

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: catest
          POSTGRES_PASSWORD: catest
          POSTGRES_DB: catest
        options: >-
          --health-cmd pg_isready

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Install dependencies
        run: go get .
      - name: Run tests
        run: go test -coverprofile=cover.out cucinassistant/database -args config/ci.yml
      - name: Push coverage results
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: cover.out
